services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.143.1
    volumes:
      - ./otel-config-appd.yaml:/etc/otel/config.yaml
    command: --config /etc/otel/config.yaml
    environment:
      - JAEGER_ENDPOINT=jaeger:4317
      - APPD_ACCOUNT
      - APPD_API_KEY
      - APPD_HOST=${APPD_ACCOUNT}.saas.appdynamics.com
      - APPD_PORT=443
      - APPD_REGION=pdx
    ports:
      - "1777:1777"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "13133:13133" # health_check extension
      - "55679:55679" # zpages extension
      - "4317:4317"   # OTLP gRPC receiver
      - "8889:8889"   # Prometheus metrics exporter (scrape endpoint)
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.76.0
    ports:
      - "16686:16686"
